spring.application.name=springboot-service

# Server Port
server.port=8088

# PostgreSQL Database Configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/issue_tracker
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=2106
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# H2 Console Settings (Disabled)
spring.h2.console.enabled=false

# JPA Hibernate Settings
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# FastAPI Integration Client Settings
fastapi.service.url=http://localhost:8000

# HikariCP Configuration to prevent 'connection lost'
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.leak-detection-threshold=60000
